### ISSUE TITLE
Add Pause Button

### ISSUE THREAD

**Issue by dbanbahji** [overshard/timelite#47]
I feel like it can use a pause button, id love to implement it with some help. Let me know what you think, thanks.

**Comment by dbanbahji** [comment]
More of a feature request, i dont think i can add those labels.

**Comment by overshard** [comment]
Hello, thank you for the input! I don't like the idea of a pause button. The point of timelite is to log all time, if you step away to do something else or need to swap focus then you are still doing something that could be logged as time. Instead of pausing my workflow is to add current time and then do the other task or step away and then when I come back I can either clear the new time that has accumulated or log that time if needed. I think adding a pause button just increases complexity and leads to issues of people forgetting to start the timer again when they come back and then having no time to log at all.
